### ISSUE TITLE
Does not work anymore on most sites in 46.0.2485.0 Canary

### ISSUE THREAD

**Issue by vsemozhetbyt** [davidparsson/ScrollbarAnywhere#44] opened 2015-08-17 11:40 UTC
For example, in the Facebook or Twitter. Cursor turns in hand form, debug messages are common, but no scroll happens.

**Comment by davidparsson** [comment] 2015-08-17 11:47
Thanks for reporting. Do you see any errors in the JavaScript console? What OS are you on, and what button are you using to scroll?

**Comment by vsemozhetbyt** [comment] 2015-08-17 11:59
Windows 7 SP1. Usually I use the right button, but middle does not work now as well (though both work on the extension option/test page). No error messages in the console, just these ones:

![1](https://cloud.githubusercontent.com/assets/10393198/9304406/8d3ae568-44f0-11e5-9d9c-dd81bd1b22ef.png)

**Comment by vsemozhetbyt** [comment] 2015-08-17 12:08
And tere are some, if I select "Developer mode" in the "Manage extensions" page and then click on the "Inspect views: background page" in the "Scrollbar Anywhere" section.

![2](https://cloud.githubusercontent.com/assets/10393198/9304535/d5a597e8-44f1-11e5-9b4c-08b33fc64d92.png)

**Comment by davidparsson** [comment] 2015-08-18 12:40
Thanks, I'll see what I can do!

I'm rather busy now so I'm not sure when I'll find the time to look at this. If you're willing, I'll gladly accept pull requests.

**Comment by vsemozhetbyt** [comment] 2015-08-18 13:18
Thank you for the answer. Unfortunately, I am a novice in the Chrome and its extension and have not much experience here. Sorry. Good luck in fixing in the suitable time :)

**Comment by deathtrip** [comment] 2015-11-17 19:45
so... is this extension oficially dead?

**Comment by davidparsson** [comment] 2015-11-17 20:23
Well, sort of. It's really hard for me to find any time to work on this.

I'm guessing this is still an issue? Pull requests are gladly accepted.

**Comment by davidparsson** [comment] 2015-11-22 12:33
I've tried to reproduce this today using the latest Chrome Canary version (49.0.2571.0, 64-bit on Windows), but to me it all seems to be working fine.

Can you please give me a more detailed description on your setup, settings and web pages that are having issues?

**Comment by vsemozhetbyt** [comment] 2015-11-22 12:51
It's strange. Suddenly, it works fine with all the sites for me in 49.0.2571.0 Сanary (64-bit) on Win 7 x64.  May be some experimental Сanary feature has just gone away or changed. Thank you for your try this time.

**Comment by vsemozhetbyt** [comment] 2015-11-22 12:54
My settings:

![s](https://cloud.githubusercontent.com/assets/10393198/11323891/f864a26e-9128-11e5-9acb-4f330414147e.png)

**Comment by davidparsson** [comment] 2015-11-22 13:06
Thanks, I'll close this issue then, since it seems to be resolved. Please let me know if it's not.

**Closed by davidparsson** 2015-11-22 13:06 UTC
Labels: Bug, More details needed
